language: go

go:
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - tip

before_install:
  - cd machinery
  - go mod download

script:
  - go vet
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)